pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=GitHub CI - ci-and-cd
    actions:
      merge:
        method: merge
