name: CI/CD

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  # trigger by manually
  # eslint-disable-next-line yml/no-empty-mapping-value
  workflow_dispatch:

jobs:
  # use eslint to check the code quality
  lint:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [17.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache ~/.pnpm-store
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          # eslint-disable-next-line max-len
          key: ${{ runner.os }}-${{ matrix.node-version }}-test-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.node-version }}-test-
            ${{ runner.os }}-
      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm i

      - name: Run lint
        run: pnpm run lint

      - name: Run build
        run: pnpm run build
        env:
          OWNER: ${{ github.actor }}
          # REPO: ${{ github.repository.name }}
          REPO: qianx1.xyz

  # if lint is successful, deploy to vercel
  deploy:
    # judge if the lint is successful
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20 # deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} # Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-args: --prod # Optional
          working-directory: ./sub-directory
          alias-domains: | # Optional
            qianx1.xyz
            ${{ github.repository.name }}-qianxi.vercel.app
        env:
          OWNER: ${{ github.actor }}
          # REPO: ${{ github.repository.name }}
          REPO: qianx1.xyz
